I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "game/gallery.rpy", line 150, in execute
    screen gallery():
  File "game/gallery.rpy", line 150, in execute
    screen gallery():
  File "game/gallery.rpy", line 180, in execute
    for r in replays:
  File "game/gallery.rpy", line 181, in execute
    if (filter_scene == "all" or filter_scene in r[4]) and (filter_girl == "all" or filter_girl in r[5]):
  File "game/gallery.rpy", line 185, in execute
    for s in r[6]:
  File "game/gallery.rpy", line 186, in execute
    $ local_dict.update({s : getattr(store, s)})
  File "game/gallery.rpy", line 186, in <module>
    $ local_dict.update({s : getattr(store, s)})
AttributeError: 'StoreModule' object has no attribute 'namelong'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\saber\Documents\Eternum V0.8.0-PC\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/gallery.rpy", line 150, in execute
    screen gallery():
  File "game/gallery.rpy", line 150, in execute
    screen gallery():
  File "game/gallery.rpy", line 180, in execute
    for r in replays:
  File "game/gallery.rpy", line 181, in execute
    if (filter_scene == "all" or filter_scene in r[4]) and (filter_girl == "all" or filter_girl in r[5]):
  File "game/gallery.rpy", line 185, in execute
    for s in r[6]:
  File "game/gallery.rpy", line 186, in execute
    $ local_dict.update({s : getattr(store, s)})
  File "game/gallery.rpy", line 186, in <module>
    $ local_dict.update({s : getattr(store, s)})
AttributeError: 'StoreModule' object has no attribute 'namelong'

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Eternum 0.8.0
Sun Dec 22 00:58:31 2024
